const device=document.querySelector('#device'),token=document.querySelector('#token'),status=document.querySelector('#status'),notice=document.querySelector('#notice'),shots=document.querySelector('#shots'),refreshShots=document.querySelector('#refreshShots'),previousShot=document.querySelector('#previousShot'),nextShot=document.querySelector('#nextShot'),shotPosition=document.querySelector('#shotPosition');
const tapActions=document.createElement('div'),remoteTap=document.createElement('button'),continuousTap=document.createElement('button'),confirmTap=document.createElement('button'),cancelTap=document.createElement('button');tapActions.className='tap-actions';remoteTap.textContent='單次遠端點擊';remoteTap.disabled=true;continuousTap.textContent='連續點擊模式';continuousTap.disabled=true;confirmTap.textContent='確認點擊';cancelTap.textContent='取消';confirmTap.hidden=true;cancelTap.hidden=true;tapActions.append(remoteTap,continuousTap,confirmTap,cancelTap);document.querySelector('.shot-nav').after(tapActions);
const remoteNav=document.createElement('div'),navBack=document.createElement('button'),navHome=document.createElement('button'),navRecents=document.createElement('button');remoteNav.className='remote-nav';remoteNav.hidden=true;navRecents.innerHTML='<span class="nav-symbol recents-symbol"></span><span>Recents</span>';navHome.innerHTML='<span class="nav-symbol home-symbol"></span><span>Home</span>';navBack.innerHTML='<span class="nav-symbol back-symbol"></span><span>Back</span>';remoteNav.append(navRecents,navHome,navBack);tapActions.after(remoteNav);
const clearTakeover=document.createElement('button');clearTakeover.className='red wide';clearTakeover.dataset.command='CLEAR_TAKEOVER';clearTakeover.textContent='解除 Takeover 狀態';document.querySelector('.grid').append(clearTakeover);
let shotUrl='',shotList=[],shotIndex=0,currentShot=null,tapMode=false,tapPoint=null,continuousMode=false,continuousBusy=false,continuousExpiryTimer=0;
token.value=sessionStorage.token||'';token.onchange=()=>{sessionStorage.token=token.value};
device.onchange=()=>{if(continuousMode)void stopContinuousMode();shotList=[];shotIndex=0;currentShot=null;if(shotUrl){URL.revokeObjectURL(shotUrl);shotUrl=''}shots.innerHTML='<div class="empty">按「查看最新截圖」後才會載入</div>';updateShotNavigation();updateRemoteTapAvailability();void refresh()};
const authHeaders=()=>({authorization:'Bearer '+token.value});
async function refresh(){updateRemoteTapAvailability();try{const r=await fetch('/api/control/status?device='+encodeURIComponent(device.value));const j=await r.json(),x=j.status;if(!x){renderStatus(null,0,true,'裝置未連線');syncControls(null,true);return}const age=Math.max(0,Math.floor((j.serverTime-x.lastSeen)/1000)),offline=age>15;renderStatus(x,age,offline);syncControls(x,offline)}catch(e){renderStatus(null,0,true,'連線錯誤');syncControls(null,true)}}
function renderStatus(x,age,offline,error=''){status.className='status-panel';status.replaceChildren();const head=document.createElement('div');head.className='status-head';const identity=document.createElement('div');identity.className='status-identity';const dot=document.createElement('span');dot.className='status-dot '+(offline?'is-offline':'is-online');const name=document.createElement('strong');const stateNames={IN_GAME:'遊戲中'};name.textContent=error||(offline?'裝置離線':stateNames[x.status]||x.status||'ONLINE');identity.append(dot,name);const seen=document.createElement('span');seen.className='last-seen';seen.textContent=x?`最後連線 ${age} 秒前`:'尚未收到裝置狀態';head.append(identity,seen);status.append(head);if(!x)return;const when=t=>t?new Date(t).toLocaleString():'未曾辨識',screen={ON:'亮屏',OFF:'關屏',LOCKED:'已鎖定'}[x.screenState]||'—',game=x.gameState==='FOREGROUND'?'前景':'背景',shot=(x.lastScreenshotResult||'尚未截圖')+(x.screenshotErrorCount?` · 連續錯誤 ${x.screenshotErrorCount}`:''),hasTicketQuantity=x.ticketQuantity>=0,ticketQuantity=hasTicketQuantity?Number(x.ticketQuantity).toLocaleString():'未辨識';const items=[['Watchdog',x.watchdogEnabled?'已啟用':'已停用',x.watchdogEnabled?'good':'neutral'],['刷關',x.farmRunning?'進行中':'已停止',x.farmRunning?'good':'neutral'],['自動刷券',x.ticketAutoEnabled?'已啟用':'已禁用',x.ticketAutoEnabled?'good':'neutral'],['A 掣狀態',x.ticketKnown?(x.ticketRunning?'ON':'OFF'):'未偵測',x.ticketKnown&&x.ticketRunning?'good':'neutral'],['券數量',ticketQuantity,'neutral'],['卡死偵測',x.freezeState||'等待檢查',/卡死|重啟/.test(x.freezeState||'')?'bad':/正常/.test(x.freezeState||'')?'good':'neutral'],['最後卡死',when(x.lastFreezeDetectedAt),'neutral'],['最後 Recovery',when(x.lastRecoveryAt),'neutral'],['屏幕',screen,screen==='亮屏'?'good':'neutral'],['遊戲',game,game==='前景'?'good':'neutral'],['最後截圖',shot,x.screenshotErrorCount?'bad':'neutral'],['刷關步驟',x.farmStep||'—','neutral'],['最後操作',x.lastFarmActionAt?`${x.lastFarmAction} · ${when(x.lastFarmActionAt)}`:'—','neutral'],['失敗關卡最後辨識',when(x.lastStageFailureDetectedAt),'neutral'],['其他裝置登入最後辨識',when(x.lastTakeoverDetectedAt),'neutral']];const grid=document.createElement('div');grid.className='status-grid';for(const [label,value,tone] of items){const tile=document.createElement('div');tile.className='status-tile';const l=document.createElement('span');l.className='status-label';l.textContent=label;const v=document.createElement('strong');v.className='status-value '+tone;if(label==='券數量'&&hasTicketQuantity){const count=document.createElement('span');count.className='ticket-count';count.textContent=value;const at=document.createElement('span');at.className='ticket-time';at.textContent=when(x.ticketQuantityAt);v.append(count,at)}else v.textContent=value;tile.append(l,v);grid.append(tile)}status.append(grid)}
function syncControls(x,offline){document.querySelectorAll('[data-command]').forEach(b=>{if(b.classList.contains('pending'))return;const c=b.dataset.command;let disabled=offline;if(x&&!offline){if(c==='ENABLE_WATCHDOG')disabled=!!x.watchdogEnabled;if(c==='DISABLE_WATCHDOG')disabled=!x.watchdogEnabled;if(c==='RELOGIN_HOME'||c==='CLEAR_TAKEOVER')disabled=x.status!=='REMOTE_TAKEOVER';if(c==='START_FARM')disabled=!!x.farmRunning||!x.watchdogEnabled;if(c==='STOP_FARM')disabled=!x.farmRunning;if(c==='START_TICKET')disabled=!!x.ticketAutoEnabled||!x.watchdogEnabled;if(c==='STOP_TICKET')disabled=!x.ticketAutoEnabled}b.disabled=disabled})}
async function loadShots(){
  refreshShots.disabled=true;shots.innerHTML='<div class="empty">載入截圖中…</div>';
  try{
    const r=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=200');
    if(!r.ok)throw Error(await r.text());
    shotList=(await r.json()).screenshots;shotIndex=0;await showShot();
  }catch(e){shotList=[];currentShot=null;shots.innerHTML='<div class="empty">載入失敗：'+String(e.message).replace(/[<>]/g,'')+'</div>';updateShotNavigation();updateRemoteTapAvailability()}finally{refreshShots.disabled=false}
}
async function showShot(){if(continuousMode){tapPoint=null;shots.querySelector('.tap-marker')?.remove()}else exitTapMode();if(shotUrl){URL.revokeObjectURL(shotUrl);shotUrl=''}shots.replaceChildren();if(!shotList.length){currentShot=null;shots.innerHTML='<div class="empty">未有歷史截圖</div>';updateShotNavigation();updateRemoteTapAvailability();return}const item=shotList[shotIndex];currentShot=item;const imageResponse=await fetch('/api/control/screenshots/'+item.id);if(!imageResponse.ok)throw Error(await imageResponse.text());shotUrl=URL.createObjectURL(await imageResponse.blob());const card=document.createElement('div');card.className='shot';const img=document.createElement('img');img.src=shotUrl;img.alt=item.event+'遊戲截圖';img.onclick=selectTapPoint;const meta=document.createElement('div');meta.className='shot-meta';meta.textContent=new Date(item.capturedAt).toLocaleString()+' · '+item.event;card.append(img,meta);shots.append(card);if(continuousMode)shots.classList.add('tap-mode');updateShotNavigation();updateRemoteTapAvailability()}
function updateShotNavigation(){previousShot.disabled=continuousMode||!shotList.length||shotIndex>=shotList.length-1;nextShot.disabled=continuousMode||!shotList.length||shotIndex===0;shotPosition.textContent=shotList.length?`${shotIndex+1} / ${shotList.length}`:'—'}
previousShot.onclick=async()=>{if(shotIndex<shotList.length-1){shotIndex++;await showShot()}};
nextShot.onclick=async()=>{if(shotIndex>0){shotIndex--;await showShot()}};
remoteTap.onclick=()=>{if(!token.value){notice.textContent='請先輸入 Control token';return}if(!currentShot){notice.textContent='請先查看最新截圖';return}const age=Date.now()-currentShot.capturedAt;if(age<0||age>60_000){notice.textContent='截圖已超過60秒，請先擷取或載入最新截圖';return}tapMode=true;tapPoint=null;remoteTap.hidden=true;continuousTap.hidden=true;confirmTap.hidden=true;cancelTap.hidden=false;shots.classList.add('tap-mode');notice.textContent='請點擊截圖，點選後會立即執行'};
cancelTap.onclick=()=>{exitTapMode();notice.textContent='已取消遠端點擊'};
continuousTap.onclick=async()=>{if(continuousMode){await stopContinuousMode();return}if(!token.value){notice.textContent='請先輸入 Control token';return}if(!currentShot||Date.now()-currentShot.capturedAt>60_000){notice.textContent='請先載入60秒內的最新截圖';return}continuousTap.disabled=true;notice.textContent='正在啟動連續點擊模式…';try{const r=await queueCommand('START_REMOTE_CONTROL');if(!r.ok)throw Error(await r.text());continuousMode=true;tapMode=true;continuousTap.textContent='退出連續點擊';continuousTap.classList.add('red');remoteTap.hidden=true;remoteNav.hidden=false;shots.classList.add('tap-mode');updateShotNavigation();resetContinuousExpiry();notice.textContent='連續點擊模式已啟動，請直接點擊截圖'}catch(e){notice.textContent='無法啟動連續模式：'+e.message}finally{continuousTap.disabled=false}};
async function stopContinuousMode(){continuousMode=false;continuousBusy=false;tapMode=false;tapPoint=null;clearTimeout(continuousExpiryTimer);continuousExpiryTimer=0;continuousTap.textContent='連續點擊模式';continuousTap.classList.remove('red');remoteTap.hidden=false;remoteNav.hidden=true;shots.classList.remove('tap-mode');shots.querySelector('.tap-marker')?.remove();updateShotNavigation();updateRemoteTapAvailability();notice.textContent='已退出連續點擊模式';try{await queueCommand('STOP_REMOTE_CONTROL')}catch(_){}}
function resetContinuousExpiry(){clearTimeout(continuousExpiryTimer);continuousExpiryTimer=setTimeout(async()=>{if(continuousMode){await stopContinuousMode();notice.textContent='連續點擊模式閒置1分鐘，已自動退出'}},60_000)}
async function queueCommand(command,payload){return fetch('/api/control/command',{method:'POST',headers:{...authHeaders(),'content-type':'application/json'},body:JSON.stringify({device:device.value,command,payload})})}
async function waitCommandComplete(id,seconds=30){for(let i=0;i<seconds*2;i++){await new Promise(r=>setTimeout(r,500));const r=await fetch('/api/control/commands/'+id,{headers:authHeaders()});if(!r.ok)continue;const c=await r.json();if(c.state==='COMPLETED')return c}throw Error('Android沒有在限時內完成點擊')}
async function sendContinuousTap(){if(!continuousMode||continuousBusy||!tapPoint||!currentShot)return;resetContinuousExpiry();await performContinuousCommand('TAP_AND_CAPTURE',{...tapPoint,capturedAt:currentShot.capturedAt},'點擊')}
async function performContinuousCommand(command,payload,label){if(!continuousMode||continuousBusy||!currentShot)return;continuousBusy=true;continuousTap.disabled=true;for(const b of remoteNav.querySelectorAll('button'))b.disabled=true;const previousFirst=currentShot.id;try{const r=await queueCommand(command,payload);if(!r.ok)throw Error(await r.text());const result=await waitCommandComplete((await r.json()).id);if(!/COMPLETED$/.test(result.result||''))throw Error(friendlyResult(result.result));notice.textContent=`${label}完成，正在載入新畫面…`;await waitForNewShot(previousFirst,250,20);notice.textContent='畫面已更新，可繼續操作'}catch(e){notice.textContent=`${label}失敗：`+e.message}finally{continuousBusy=false;continuousTap.disabled=false;for(const b of remoteNav.querySelectorAll('button'))b.disabled=false;updateRemoteTapAvailability()}}
navBack.onclick=()=>{resetContinuousExpiry();void performContinuousCommand('NAV_BACK_CAPTURE',null,'Back')};navHome.onclick=()=>{resetContinuousExpiry();void performContinuousCommand('NAV_HOME_CAPTURE',null,'Home')};navRecents.onclick=()=>{resetContinuousExpiry();void performContinuousCommand('NAV_RECENTS_CAPTURE',null,'Recents')};
function exitTapMode(){tapMode=false;tapPoint=null;remoteTap.hidden=false;continuousTap.hidden=false;confirmTap.hidden=true;confirmTap.disabled=true;cancelTap.hidden=true;shots.classList.remove('tap-mode');shots.querySelector('.tap-marker')?.remove();updateRemoteTapAvailability()}
function updateRemoteTapAvailability(){const unavailable=!currentShot||Date.now()-currentShot.capturedAt>60_000||Date.now()<currentShot.capturedAt;remoteTap.disabled=unavailable;continuousTap.disabled=continuousBusy||(!continuousMode&&unavailable)}
function selectTapPoint(event){if(!tapMode||continuousBusy)return;const img=event.currentTarget,rect=img.getBoundingClientRect(),scale=Math.min(rect.width/img.naturalWidth,rect.height/img.naturalHeight),contentWidth=img.naturalWidth*scale,contentHeight=img.naturalHeight*scale,left=rect.left+(rect.width-contentWidth)/2,top=rect.top+(rect.height-contentHeight)/2,x=(event.clientX-left)/contentWidth,y=(event.clientY-top)/contentHeight;if(x<0||x>1||y<0||y>1)return;tapPoint={xRatio:x,yRatio:y};let marker=shots.querySelector('.tap-marker');if(!marker){marker=document.createElement('span');marker.className='tap-marker';img.parentElement.append(marker)}const cardRect=img.parentElement.getBoundingClientRect();marker.style.left=(event.clientX-cardRect.left)+'px';marker.style.top=(event.clientY-cardRect.top)+'px';notice.textContent=`正在點擊 ${Math.round(x*1080)}, ${Math.round(y*2640)}…`;if(continuousMode)void sendContinuousTap();else void sendSingleTap()}
async function sendSingleTap(){if(!tapPoint||!currentShot||continuousBusy)return;continuousBusy=true;cancelTap.disabled=true;const previousFirst=currentShot.id;try{const r=await queueCommand('TAP_AND_CAPTURE',{...tapPoint,capturedAt:currentShot.capturedAt});if(!r.ok)throw Error(await r.text());const result=await waitCommandComplete((await r.json()).id);if(result.result!=='TAP_CAPTURE_COMPLETED')throw Error(friendlyResult(result.result));notice.textContent='點擊完成，正在載入新畫面…';await waitForNewShot(previousFirst,250,20)}catch(e){notice.textContent='單次點擊失敗：'+e.message}finally{continuousBusy=false;cancelTap.disabled=false;exitTapMode()}}
confirmTap.onclick=async()=>{if(!tapPoint||!currentShot)return;const original='確認點擊',previousFirst=currentShot.id;confirmTap.disabled=true;confirmTap.classList.add('pending');confirmTap.textContent='正在送出…';try{const r=await fetch('/api/control/command',{method:'POST',headers:{...authHeaders(),'content-type':'application/json'},body:JSON.stringify({device:device.value,command:'TAP_AND_CAPTURE',payload:{...tapPoint,capturedAt:currentShot.capturedAt}})});if(!r.ok)throw Error(await r.text());const command=await r.json();notice.textContent='點擊及截圖指令已排隊';void waitForAck(command.id,confirmTap,original,()=>waitForNewShot(previousFirst,250,20))}catch(e){confirmTap.classList.remove('pending');confirmTap.textContent=original;confirmTap.disabled=false;notice.textContent='點擊送出失敗：'+e.message}finally{tapMode=false;remoteTap.hidden=false;cancelTap.hidden=true;shots.classList.remove('tap-mode')}};
async function waitForNewShot(previousFirst,interval=5000,attempts=12){for(let attempt=1;attempt<=attempts;attempt++){notice.textContent=`等待Android截圖… ${Math.ceil(attempt*interval/1000)}秒`;await new Promise(r=>setTimeout(r,interval));const r=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=1');if(r.ok){const first=(await r.json()).screenshots[0]?.id;if(first&&first!==previousFirst){await loadShots();notice.textContent='截圖完成並已保存';return true}}}notice.textContent='截圖逾時';return false}
async function waitForAck(id,button,original,onSuccess){for(let elapsed=1;elapsed<=120;elapsed++){await new Promise(r=>setTimeout(r,1000));const r=await fetch('/api/control/commands/'+id,{headers:authHeaders()});if(!r.ok)continue;const command=await r.json();if(command.state==='EXECUTING'){button.textContent=`Android 執行中… ${elapsed}s`;notice.textContent='Android已收到，正在執行指令';continue}button.textContent=`等待 Android… ${elapsed}s`;if(command.state==='COMPLETED'){const ok=!/FAIL|ERROR|REJECTED|IGNORED|失敗|無法|未能|搵唔到|找不到|請先|不可|未見/.test(command.result||'');button.classList.remove('pending');button.classList.add(ok?'confirmed':'failed');button.textContent=ok?'✓ 執行成功':'執行失敗';notice.textContent=`Android結果：${friendlyResult(command.result)}`;setTimeout(()=>resetButton(button,original),3500);if(ok&&onSuccess)void onSuccess();void refresh();return}}button.classList.remove('pending');button.classList.add('failed');button.textContent='Android沒有完成';notice.textContent='指令在120秒內沒有完成';setTimeout(()=>resetButton(button,original),3500)}
function friendlyResult(result){const messages={IGNORED_NOT_TAKEOVER:'目前沒有偵測到其他裝置登入，毋須重新登入',REJECTED_TAKEOVER_LOCK:'其他裝置正在使用帳戶，暫時不能刷關',REJECTED_RECOVERY_IN_PROGRESS:'Watchdog 正在復原遊戲，請稍後再試',RESTART_ALREADY_RUNNING:'遊戲已經正在重新啟動',REMOTE_TAP_COMPLETED:'已完成遠端點擊',REJECTED_DEVICE_BUSY:'Android 正在復原或重新啟動，暫時不能點擊',TAKEOVER_CLEARED:'已解除 Takeover 狀態；未有點擊遊戲確認',TICKET_AUTO_ENABLED:'已啟用自動保持 A 掣 ON',TICKET_AUTO_DISABLED:'已禁用自動保持；仍會辨識 A 掣狀態'};return messages[result]||result||'完成'}
function resetButton(button,original){button.classList.remove('pending','confirmed','failed');button.textContent=original;button.dataset.busy='0';if(button===confirmTap)exitTapMode();void refresh()}
refreshShots.onclick=()=>loadShots();
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=async()=>{if(!token.value){notice.textContent='請輸入 token';return}const original=button.textContent;button.disabled=true;button.classList.add('pending');button.textContent='正在送出…';let previousFirst=null;try{if(button.dataset.command==='CAPTURE_SCREEN'){const before=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=1',{headers:authHeaders()});if(before.ok)previousFirst=(await before.json()).screenshots[0]?.id||null}const r=await fetch('/api/control/command',{method:'POST',headers:{...authHeaders(),'content-type':'application/json'},body:JSON.stringify({device:device.value,command:button.dataset.command})});if(!r.ok){button.classList.remove('pending');button.classList.add('failed');button.textContent='送出失敗';notice.textContent='失敗：'+await r.text();setTimeout(()=>resetButton(button,original),3000);return}const command=await r.json();notice.textContent='指令已排隊，等待Android接收';void waitForAck(command.id,button,original);if(button.dataset.command==='CAPTURE_SCREEN')void waitForNewShot(previousFirst)}catch(e){button.classList.remove('pending');button.classList.add('failed');button.textContent='網絡錯誤';notice.textContent=String(e.message);setTimeout(()=>resetButton(button,original),3000)}});
updateShotNavigation();refresh();setInterval(refresh,5000);
