const device=document.querySelector('#device'),token=document.querySelector('#token'),status=document.querySelector('#status'),notice=document.querySelector('#notice'),shots=document.querySelector('#shots'),refreshShots=document.querySelector('#refreshShots'),previousShot=document.querySelector('#previousShot'),nextShot=document.querySelector('#nextShot'),shotPosition=document.querySelector('#shotPosition');
let shotUrl='',shotList=[],shotIndex=0;
token.value=sessionStorage.token||'';token.onchange=()=>{sessionStorage.token=token.value};
device.onchange=()=>{shotList=[];shotIndex=0;if(shotUrl){URL.revokeObjectURL(shotUrl);shotUrl=''}shots.innerHTML='<div class="empty">按「查看最新截圖」後才會載入</div>';updateShotNavigation();void refresh()};
const authHeaders=()=>({authorization:'Bearer '+token.value});
async function refresh(){try{const r=await fetch('/api/control/status?device='+encodeURIComponent(device.value));const j=await r.json(),x=j.status;if(!x){renderStatus(null,0,true,'裝置未連線');syncControls(null,true);return}const age=Math.max(0,Math.floor((j.serverTime-x.lastSeen)/1000)),offline=age>15;renderStatus(x,age,offline);syncControls(x,offline)}catch(e){renderStatus(null,0,true,'連線錯誤');syncControls(null,true)}}
function renderStatus(x,age,offline,error=''){status.className='status-panel';status.replaceChildren();const head=document.createElement('div');head.className='status-head';const identity=document.createElement('div');identity.className='status-identity';const dot=document.createElement('span');dot.className='status-dot '+(offline?'is-offline':'is-online');const name=document.createElement('strong');name.textContent=error||(offline?'裝置離線':x.status||'ONLINE');identity.append(dot,name);const seen=document.createElement('span');seen.className='last-seen';seen.textContent=x?`最後連線 ${age} 秒前`:'尚未收到裝置狀態';head.append(identity,seen);status.append(head);if(!x)return;const items=[['Watchdog',x.watchdogEnabled?'已啟用':'已停用',x.watchdogEnabled?'good':'neutral'],['刷關',x.farmRunning?'進行中':'已停止',x.farmRunning?'good':'neutral'],['刷券',x.ticketKnown?(x.ticketRunning?'ON':'OFF'):'未偵測',x.ticketKnown&&x.ticketRunning?'good':'neutral'],['卡死偵測',x.freezeState||'等待檢查',/卡死|重啟/.test(x.freezeState||'')?'bad':/正常/.test(x.freezeState||'')?'good':'neutral']];const grid=document.createElement('div');grid.className='status-grid';for(const [label,value,tone] of items){const tile=document.createElement('div');tile.className='status-tile';const l=document.createElement('span');l.className='status-label';l.textContent=label;const v=document.createElement('strong');v.className='status-value '+tone;v.textContent=value;tile.append(l,v);grid.append(tile)}status.append(grid)}
function syncControls(x,offline){document.querySelectorAll('[data-command]').forEach(b=>{if(b.classList.contains('pending'))return;const c=b.dataset.command;let disabled=offline;if(x&&!offline){if(c==='ENABLE_WATCHDOG')disabled=!!x.watchdogEnabled;if(c==='DISABLE_WATCHDOG')disabled=!x.watchdogEnabled;if(c==='START_FARM')disabled=!!x.farmRunning||!x.watchdogEnabled;if(c==='STOP_FARM')disabled=!x.farmRunning;if(c==='START_TICKET')disabled=x.ticketKnown&&x.ticketRunning;if(c==='STOP_TICKET')disabled=x.ticketKnown&&!x.ticketRunning}b.disabled=disabled})}
async function loadShots(){
  refreshShots.disabled=true;shots.innerHTML='<div class="empty">載入截圖中…</div>';
  try{
    const r=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=200');
    if(!r.ok)throw Error(await r.text());
    shotList=(await r.json()).screenshots;shotIndex=0;await showShot();
  }catch(e){shotList=[];shots.innerHTML='<div class="empty">載入失敗：'+String(e.message).replace(/[<>]/g,'')+'</div>';updateShotNavigation()}finally{refreshShots.disabled=false}
}
async function showShot(){if(shotUrl){URL.revokeObjectURL(shotUrl);shotUrl=''}shots.replaceChildren();if(!shotList.length){shots.innerHTML='<div class="empty">未有歷史截圖</div>';updateShotNavigation();return}const item=shotList[shotIndex];const imageResponse=await fetch('/api/control/screenshots/'+item.id);if(!imageResponse.ok)throw Error(await imageResponse.text());shotUrl=URL.createObjectURL(await imageResponse.blob());const card=document.createElement('div');card.className='shot';const img=document.createElement('img');img.src=shotUrl;img.alt=item.event+'遊戲截圖';const meta=document.createElement('div');meta.className='shot-meta';meta.textContent=new Date(item.capturedAt).toLocaleString()+' · '+item.event;card.append(img,meta);shots.append(card);updateShotNavigation()}
function updateShotNavigation(){previousShot.disabled=!shotList.length||shotIndex>=shotList.length-1;nextShot.disabled=!shotList.length||shotIndex===0;shotPosition.textContent=shotList.length?`${shotIndex+1} / ${shotList.length}`:'—'}
previousShot.onclick=async()=>{if(shotIndex<shotList.length-1){shotIndex++;await showShot()}};
nextShot.onclick=async()=>{if(shotIndex>0){shotIndex--;await showShot()}};
async function waitForNewShot(previousFirst){for(let attempt=1;attempt<=12;attempt++){notice.textContent=`等待Android截圖… ${attempt*5}/60秒`;await new Promise(r=>setTimeout(r,5000));const r=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=1');if(r.ok){const first=(await r.json()).screenshots[0]?.id;if(first&&first!==previousFirst){await loadShots();notice.textContent='截圖完成並已保存';return}}}notice.textContent='截圖逾時'}
async function waitForAck(id,button,original){for(let elapsed=1;elapsed<=120;elapsed++){await new Promise(r=>setTimeout(r,1000));const r=await fetch('/api/control/commands/'+id,{headers:authHeaders()});if(!r.ok)continue;const command=await r.json();if(command.state==='EXECUTING'){button.textContent=`Android 執行中… ${elapsed}s`;notice.textContent='Android已收到，正在執行指令';continue}button.textContent=`等待 Android… ${elapsed}s`;if(command.state==='COMPLETED'){const ok=!/FAIL|ERROR|REJECTED|IGNORED|失敗|無法|未能|搵唔到|找不到|請先|不可|未見/.test(command.result||'');button.classList.remove('pending');button.classList.add(ok?'confirmed':'failed');button.textContent=ok?'✓ 執行成功':'執行失敗';notice.textContent=`Android結果：${command.result||'OK'}`;setTimeout(()=>resetButton(button,original),3500);void refresh();return}}button.classList.remove('pending');button.classList.add('failed');button.textContent='Android沒有完成';notice.textContent='指令在120秒內沒有完成';setTimeout(()=>resetButton(button,original),3500)}
function resetButton(button,original){button.classList.remove('pending','confirmed','failed');button.textContent=original;button.dataset.busy='0';void refresh()}
refreshShots.onclick=()=>loadShots();
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=async()=>{if(!token.value){notice.textContent='請輸入 token';return}const original=button.textContent;button.disabled=true;button.classList.add('pending');button.textContent='正在送出…';let previousFirst=null;try{if(button.dataset.command==='CAPTURE_SCREEN'){const before=await fetch('/api/control/screenshots?device='+encodeURIComponent(device.value)+'&limit=1',{headers:authHeaders()});if(before.ok)previousFirst=(await before.json()).screenshots[0]?.id||null}const r=await fetch('/api/control/command',{method:'POST',headers:{...authHeaders(),'content-type':'application/json'},body:JSON.stringify({device:device.value,command:button.dataset.command})});if(!r.ok){button.classList.remove('pending');button.classList.add('failed');button.textContent='送出失敗';notice.textContent='失敗：'+await r.text();setTimeout(()=>resetButton(button,original),3000);return}const command=await r.json();notice.textContent='指令已排隊，等待Android接收';void waitForAck(command.id,button,original);if(button.dataset.command==='CAPTURE_SCREEN')void waitForNewShot(previousFirst)}catch(e){button.classList.remove('pending');button.classList.add('failed');button.textContent='網絡錯誤';notice.textContent=String(e.message);setTimeout(()=>resetButton(button,original),3000)}});
updateShotNavigation();refresh();setInterval(refresh,10000);
